is_testpnc_active = TRUE;

printf("\n");

strcpy(argument, "access");
printf("access {aktsEs} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "accuset");
printf("accuset {ak" CAPITAL_U_DIAERESIS_IN_TEXT "zt ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "addeih");
printf("addeih {adE:y} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "affaire");
printf("affaire {af(f)" CAPITAL_A_DIAERESIS_IN_TEXT "r} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "affaires");
printf("affaires {af(f)" CAPITAL_A_DIAERESIS_IN_TEXT "rs} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "alcohol");
printf("alcohol {alkohOl} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "allie");
printf("allie {alI:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "alliet");
printf("alliet {alyEt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "ambient");
printf("ambient {ambyEnt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "anesthesia");
printf("anesthesia {an" SMALL_E_DIAERESIS_IN_TEXT "stEzya} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "associeit");
printf("associeit {asotsyEyt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "augos");
printf("augos {Aogos} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "aurphones");
printf("aurphones {aorfOns} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "australia");
printf("Australia {aostrAlya} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "bah");
printf("bah {ba:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "bihe");
printf("bihe {bi:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "bouquete");
printf("bouquete {bu:kEt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "bureau");
printf("bureau {b" SMALL_U_DIAERESIS_IN_TEXT "rO:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "canther");
printf("canther {kAn" SECTION_SIGN_IN_TEXT SMALL_E_DIAERESIS_IN_TEXT "r} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "cereal");
printf("cereal {ts" SMALL_E_DIAERESIS_IN_TEXT "r" SMALL_E_DIAERESIS_IN_TEXT "Al} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "christ");
printf("Christ {krist} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "claviature");
printf("claviature {klavyat" CAPITAL_U_DIAERESIS_IN_TEXT "r}||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "clientele");
printf("clientele {klyentEl} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "crimes");
printf("crimes {krims} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "corcuksnest");
printf("corcuksnest {korkUksn" SMALL_E_DIAERESIS_IN_TEXT "st} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "demonstre");
printf("demonstre {dëmOnstr(" SMALL_E_DIAERESIS_IN_TEXT ")} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "different");
printf("different {difEr" SMALL_E_DIAERESIS_IN_TEXT "nt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "dinegh");
printf("dinegh {dIn" SMALL_E_DIAERESIS_IN_TEXT "g} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "dumeb");
printf("dumeb {d" CAPITAL_U_DIAERESIS_IN_TEXT "m" SMALL_E_DIAERESIS_IN_TEXT "b} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "eet");
printf("eet {E" SMALL_E_DIAERESIS_IN_TEXT "t} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "eih");
printf("eih {e:y} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "emigrant");
printf("emigrant {emigrAnt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "enderkweiten");
printf("enderkweiten {end" SMALL_E_DIAERESIS_IN_TEXT "rkwEyt" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "eust");
printf("eust {" SMALL_O_DIAERESIS_IN_TEXT "st} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "evacue");
printf("evacue {evak" CAPITAL_U_DIAERESIS_IN_TEXT ":} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "fablieau");
printf("fablieau {fabliO:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "faire");
printf("faire {f" SMALL_A_DIAERESIS_IN_TEXT "r} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "faires");
printf("faires {f" SMALL_A_DIAERESIS_IN_TEXT "rs} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "fianceo");
printf("fianceo {fyantsEo} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "fianceos");
printf("fianceos {fyantsEos} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "finesd");
printf("finesd {fIn" SMALL_E_DIAERESIS_IN_TEXT "sd} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "firasat");
printf("firasat {firazAt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gandul");
printf("gandul {gandUl} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "garuy");
printf("garuy {garUy} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gep");
printf("gep {djep} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "ginchu");
printf("ginchu {djIntcu} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "glanez");
printf("glanez {glAn" SMALL_E_DIAERESIS_IN_TEXT "z} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gnoh");
printf("gnoh {nyo:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gordos");
printf("gordos {gOrdos} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gouverne");
printf("gouverne {gu:vErn} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "gouvernement");
printf("gouvernement {gu:vErn" SMALL_E_DIAERESIS_IN_TEXT "m" SMALL_E_DIAERESIS_IN_TEXT "nt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "guranew");
printf("guranew {gurAn" SMALL_E_DIAERESIS_IN_TEXT "w} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "habe");
printf("habe {hab} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "hehlp");
printf("hehlp {he:lp} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "hellen");
printf("hellen {hEl" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "hotel");
printf("hotel {hotEl} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "ieu");
printf("ieu {y" SMALL_O_DIAERESIS_IN_TEXT "} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "incandescent");
printf("incandescent {inkandEs" SMALL_E_DIAERESIS_IN_TEXT "nt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "*incandescente");
printf("incandescente {inkand" SMALL_E_DIAERESIS_IN_TEXT "sEnt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "insule");
printf("insule {Ins" SMALL_U_DIAERESIS_IN_TEXT "l} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "insules");
printf("insules {Ins" SMALL_U_DIAERESIS_IN_TEXT "ls} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "jaal");
printf("jaal {jaAl} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "jamiyen");
printf("jamiyen {jamIy" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kayak");
printf("kayak {kayAk} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kheiss");
printf("kheiss {qeys} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kibrit");
printf("kibrit {kIbrit} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kierey");
printf("kierey {kyerEy} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kmehen");
printf("kmehen {kmEh" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kohlen");
printf("kohlen {kO:l" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kussen");
printf("kussen {kUs" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "kwinew");
printf("kwinew {kwIn" SMALL_E_DIAERESIS_IN_TEXT "w} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "lambhel");
printf("lambhel {lAmb" SMALL_E_DIAERESIS_IN_TEXT "l} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linak");
printf("linak {linAk} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linakw");
printf("linakw {linAkw} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linek");
printf("linek {lIn" SMALL_E_DIAERESIS_IN_TEXT "k} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "lineku");
printf("lineku {linEku} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekw");
printf("linekw {lIn" SMALL_E_DIAERESIS_IN_TEXT "kw} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwe");
printf("linekwe {linEkw" SMALL_E_DIAERESIS_IN_TEXT "} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwmos");
printf("linekwmos {linEkumos} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwms");
printf("linekwms {linEkums} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwnt");
printf("linekwnt {linEkunt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwo");
printf("linekwo {linEkwo} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekws");
printf("linekws {linEkus} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwt");
printf("linekwt {linEkut} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linekwte");
printf("linekwte {linEkut} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwes");
printf("linkwes {lInkw" SMALL_E_DIAERESIS_IN_TEXT "s} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwmos");
printf("linkwmos {lInkumos} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwms");
printf("linkwms {lInkums} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwnt");
printf("linkwnt {lInkunt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwo");
printf("linkwo {lInkwo} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkws");
printf("linkws {lInkus} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwt");
printf("linkwt {lInkut} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "linkwte");
printf("linkwte {lInkut} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "mecret");
printf("*mecret {mEkr" SMALL_E_DIAERESIS_IN_TEXT "t} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "merit");
printf("merit {mErit} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "monte");
printf("monte {mont} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "moor");
printf("moor {moOr} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "mundialect");
printf("mundialect {mundyAl" SMALL_E_DIAERESIS_IN_TEXT "kt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "nest");
printf("nest {nest} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "november");
printf("november {novEmb" SMALL_E_DIAERESIS_IN_TEXT "r} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "ocean");
printf("ocean {ots(" SMALL_E_DIAERESIS_IN_TEXT ")An} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "oeti");
printf("oeti {Oyti} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "okwi");
printf("okwi {Okwi} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "ouvert");
printf("ouvert {U:v" SMALL_E_DIAERESIS_IN_TEXT "rt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "permission");
printf("permission {p" SMALL_E_DIAERESIS_IN_TEXT "rmisyOn} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "perry");
printf("perry {pEr(r)i} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "peruca");
printf("peruca {p" SMALL_E_DIAERESIS_IN_TEXT "rUka} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "plateau");
printf("plateau {platO:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "plateaus");
printf("plateaus {platO:s} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "philosophia");
printf("philosophia {filozOfya} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "pregen");
printf("pregen {prEdj" SMALL_E_DIAERESIS_IN_TEXT "n} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "prient");
printf("prient {pryent} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "prodah");
printf("prodah {prodA:} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "quis");
printf("quis {kis} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "quod");
printf("quod {kwod} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "reling");
printf("reling {rEling} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "resignet");
printf("resignet {r" SMALL_E_DIAERESIS_IN_TEXT "zIny" SMALL_E_DIAERESIS_IN_TEXT "t} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "sambahsa");
printf("sambahsa {sambA:sa} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "scafold");
printf("scafold {skafOLd} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "schebeck");
printf("schebeck {c" SMALL_E_DIAERESIS_IN_TEXT "bEk} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "schives");
printf("schives {civz} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "science");
printf("science {syents} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "sehkwnt");
printf("sehkwnt {sE:kunt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "shienciu");
printf("shienciu {xyEntsyu} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "siuk");
printf("siuk {syuk} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "sofa");
printf("sofa {sOfa} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "studyent");
printf("studyent {stUdy" SMALL_E_DIAERESIS_IN_TEXT "nt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "studyents");
printf("studyents {stUdy" SMALL_E_DIAERESIS_IN_TEXT "nts} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "studient");
printf("*studient {studyEnt} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "studients");
printf("*studients {studyEnts} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "suadin");
printf("suadin {swadIn} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "taslime");
printf("taslime {taslIm} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "tawsiend");
printf("tawsiend {tawsyEnd} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "territorium");
printf("territorium {territOryum} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "tranchee");
printf("tranchee {trantcE" SMALL_E_DIAERESIS_IN_TEXT "} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "tsui");
printf("tsui {tswi} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "udtwac");
printf("udtwac {udtwAk} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "uperlites");
printf("uperlites {" SMALL_U_DIAERESIS_IN_TEXT "p" SMALL_E_DIAERESIS_IN_TEXT "rlIts} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "urgence");
printf("urgence {urdjEnts} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "urgences");
printf("urgences {urdjEnts" SMALL_E_DIAERESIS_IN_TEXT "s} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "vrehsch");
printf("vrehsch {vre:c} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "wakea");
printf("wakea {wakEa} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "wehrgeih");
printf("wehrgeih {we:rdjE:y} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "xiongbu");
printf("xiongbu {ksyOngbu} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "yoinkjiae");
printf("yoinkjiae {yoynkjiAy} ||| ");
	printf("%s\n", pronunciation ());
strcpy(argument, "zoo");
printf("zoo {dzOo} ||| ");
	printf("%s\n", pronunciation ());

is_testpnc_active = FALSE;
